### ISSUE TITLE
Add styling for Vala Panel Appmenu bold app names

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-artwork#10]
Vala Panel Appmenu 0.5.3 is now available for Ubuntu MATE 17.10 daily and bold app names are enabled, but they require CSS styling. See https://github.com/rilian-la-te/vala-panel-appmenu/issues/81 and https://github.com/rilian-la-te/vala-panel-appmenu/commit/1192314c5121105a6ee9aefbd2fcd106c4372a2b for reference.

Switching to the Cupertino, Mutiny or Contemporary layout via MATE Tweak will enable the Global Menu provided by Vala Panel Appmenu. This change is required for all 3 themes.

Tagging @raveit65

**Comment by raveit65** [comment]
I will add suggested style classes to themes.

**Comment by raveit65** [comment]
Please test https://github.com/ubuntu-mate/ubuntu-mate-artwork/commit/8c3dc132dae824a499ecd2736127499b0649bc9d

**Comment by flexiondotorg** [comment]
Much better :-) Confirmed working in all 3 themes. Thank you!
