### ISSUE TITLE
Style na-tray applets so they more closely resemble Indicators 

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-artwork#11]
This issue affects all 3 themes. As you can see from the image below na-tray applets are squashed together when compared to Indicators. 

![na-tray and intdicators](https://user-images.githubusercontent.com/304639/29366375-c56537b4-8291-11e7-9dd5-68cfcd74548a.png)

In the screenshot above icons on the left are na-tray applets, Gitter, Rocket Chat and Slack, MATE Volume Applet.

When clicked Indicators have a button styling, similar to to the menubar in the panel. Ideally na-tray applets should be similarly button styled when clicked. At the very least na-tray applets should have padding/margins so they are at least spaced apart like Indicators.

**Comment by raveit65** [comment]
I can add a horz. padding = 1px.
A larger value will break the *outline* styling, what you see if you use tabbing with the keyboard.
1px is used by MATE themes for references.

**Comment by raveit65** [comment]
Please try https://github.com/ubuntu-mate/ubuntu-mate-artwork/commit/ccccca25eb6850185a8da717b0bb5efc5a76a8c7
This is all i can do from my side.
If Rocket Chat and Slack displays so huge again with my commit than it is a problem with the tray-applet/icons/SNI-Support or what ever.

**Comment by flexiondotorg** [comment]
OK, looks like this is a tray-applet issue then. No change. I have SNI disabled in ubuntu-mate.
