### ISSUE TITLE
Port focus ring from Ambiance

### ISSUE THREAD

**Issue by ghost** [ubuntu-mate/ubuntu-mate-artwork#12]
Ambiance has a nice, colored focus ring around labels in selected check buttons and notebook tabs, while our themes have an almost unnoticeable dashed outline.

![jj](https://user-images.githubusercontent.com/13562431/29371699-710c4b4c-827f-11e7-9927-57a611ab9d1a.jpg)
![fff](https://user-images.githubusercontent.com/13562431/29371701-7312e72a-827f-11e7-9c51-86b3c4920956.jpg)

**Comment by flexiondotorg** [comment]
Sorry, I'm really not interested in adding styling like this.

**Comment by ghost** [comment]
Got it working for check buttons, are you still not interested? It increases accessibility and visibility.
![sem titulo](https://user-images.githubusercontent.com/13562431/29377143-3dd195c2-8291-11e7-9720-d335a27cb97c.jpg)

**Comment by lah7** [comment]
For reference, Ambiant-MATE in 16.04 does have a focus ring around labels (but not the whole button itself for the checkbox)

![image](https://user-images.githubusercontent.com/13032135/29378889-a0a905e6-82b8-11e7-8d19-eae7108c333b.png)

![image](https://user-images.githubusercontent.com/13032135/29378893-a2070bc2-82b8-11e7-8b8c-ccbc079473d6.png)

In fact, many other GTK2 themes have styling to distinguish that it's in focus. I'm not sure about other GTK3 themes or 17.04/17.10 at the moment though.

![image](https://user-images.githubusercontent.com/13032135/29378928-bc1a79cc-82b8-11e7-88f5-134fb2406d87.png) ![image](https://user-images.githubusercontent.com/13032135/29378931-bdcd01c2-82b8-11e7-83d3-9c104966d59c.png) ![image](https://user-images.githubusercontent.com/13032135/29378935-bf4bfa12-82b8-11e7-8be2-fd0534b08e93.png) ![image](https://user-images.githubusercontent.com/13032135/29378936-c0b619fa-82b8-11e7-8a6d-e7c4b9638a61.png)

**Comment by ghost** [comment]
Oh yes, Ambiance and GTK2 Ambiant-MATE only does focus ring for the label but i had problems with it. I will post the code later.

**Comment by lah7** [comment]
Cross-referenced again, it seems that GTK3 doesn't show the focused state unless you are using keyboard navigation. When using the mouse, the focused part isn't shown, so I don't see why we can't have this for accessibility @flexiondotorg?

![image](https://user-images.githubusercontent.com/13032135/29380028-44bcb3f0-82bc-11e7-8857-ce1a1bbfce11.png)

![image](https://user-images.githubusercontent.com/13032135/29380031-45ff52cc-82bc-11e7-9c0b-2acb0c0052eb.png)

:point_up: When using tab, the focused styling appears.

**Comment by flexiondotorg** [comment]
@mrnhmath I am aware that 16.04 had the focus ring, I think it looks ugly. Sorry :-) But I don't want to deter you from looking at other area of improvement in the Ubuntu MATE themes. We can certainly use the help!

@lah7 We've add focus state when tabbing since you do need something to indicate what has focus when not selecting with a point device.

**Comment by ghost** [comment]
If anyone's interested, you can add the focus ring to checkbuttons by adding this to gtk-widgets.css, in the bottom of "check and radio" section:

/* Draw a focus ring around the contained label ... */
checkbutton.text-button label {
    border: 1px solid transparent;
    border-radius: 5px;
}

checkbutton.text-button:focus label {
    border-color: @focus_color;
    background-color: @focus_bg_color;
}

/* ... unless it's a proper button, which already has a focus-colored border */
button.text-button:focus label {
    border: none;
    background: none;
}

![sem titulo](https://user-images.githubusercontent.com/13562431/29427922-e2344a30-837a-11e7-9034-6b6c8cb9b4f1.jpg)

And for tabs, add this to the bottom of "notebook" section:

/* Draw a focus ring around labels in tabs */
notebook header tab label {
    border: 1px solid transparent;
    border-radius: 5px;
}

notebook:focus tab:checked label {
    border-color: @focus_color;
    background-color: @focus_bg_color;
}

![sem titulo2](https://user-images.githubusercontent.com/13562431/29428674-965fd428-837d-11e7-9d41-a2ca6982595e.jpg)

**Comment by fitojb** [comment]
We’ve got a bug report at LibreOffice when a user complained that the almost invisible focus styling in Ambiance (and thus this theme) deters a11y. Please consider adding this styling. For me it’s also a usability nightmare.

See also https://bugs.launchpad.net/ubuntu/+source/ubuntu-themes/+bug/1537047/

**Comment by ghost** [comment]
@fitojb can LO render correctly my focus ring code?
