### ISSUE TITLE
gThumb headers bars have incorrectly rendered corners

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-artwork#16]
gThumb has incorrectly rendered corners in it's header bar. See the slight pointed corner where they should be curved. All 3 Ubuntu MATE themes are affected and also Blue submarine and Green submarine. Here is a screenshot.

![gthumb](https://user-images.githubusercontent.com/304639/29625705-5cf929d6-8824-11e7-8676-62ce91c972e5.png)

@raveit65 Is it possible the minimum headerbar height that was added recently has an effect on this?

**Comment by raveit65** [comment]
No, i think this is a wrong usage of **titlebar** selector, see gtk3-inspector
![gthumb](https://user-images.githubusercontent.com/961604/29627507-990a9320-8832-11e7-9c6b-a22004932261.png)
titlebar is here the parent of *headerbar*.
Normal it is used like this *headerbar.titlebar*.
I will see if i can fix that nonsense....

**Comment by raveit65** [comment]
Please test
https://github.com/ubuntu-mate/ubuntu-mate-artwork/commit/e953e5268697d20e7678e6c2121f740e60e0bd59
Hopefully i create no collateral damage :-)

**Comment by flexiondotorg** [comment]
I can still see something that is making the header bar have squared corners. That said every other theme I've tested gives gThumb squared corners on the headerbar.

![gthumb-headerbar](https://user-images.githubusercontent.com/304639/29753253-19f84538-8b65-11e7-9a67-5e67d23e4400.png)

I agree this is an upstream issue.
