### ISSUE TITLE
Draw buttons around close icons in notebooks when hovering

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-artwork#17]
Close icons (the crosses) in notebooks should have a button drawn around them when hovered over, just like the speaker and microphone icons and toolbar icons do in Page 2 of `gtk3-widget-factory`. 

@raveit65 This issue affects all three themes.

**Comment by raveit65** [comment]
@flexiondotorg 
I will take a look into it and i hope it is possible.
No promise for application like firefox or openoffice as they do not use Gtk-Widgets in favor of their own baked gtk3 stuff.

**Comment by flexiondotorg** [comment]
I'm really only interested in proper GTK applications, in particular Pluma, Caja, MATE Terminal.

It is possible, the Ambiance theme does it. But it is not very pretty 😉

**Comment by raveit65** [comment]
@flexiondotorg 
It seems to be possible to use another icon as we have a selector here for the notebook  tab-button.
In general the icon arew defined by the icon theme, so i am still wondering that Ambiance use a different icon. ubuntu-mono-dark theme use the same icon for window-close icon here.
And i see the same icon in caja tabs with Ambiant-Mate or Ambiance.
Screenshot of the icon in Ambiance plesase?

> just like the speaker and microphone icons and toolbar icons do in Page 2 of gtk3-widget-factory.

So you like to see a colored cross? ie. green for Ambiat/Radiant-MATE ?

**Comment by flexiondotorg** [comment]
@raveit65 The monochrome  close icon that is being used by Ambiant-MATE, Radiant-MATE and Ambiant-MATE-Dark should continue to be used. It looks like this currently:

![notebooks](https://user-images.githubusercontent.com/304639/32943381-d7cfeee0-cb83-11e7-869c-bf861be3a782.png)

What I am requesting is the close icon has a button surround added when hovered over. You can use Notifications to demonstrate the intended result, like this:

![notify-example](https://user-images.githubusercontent.com/304639/32943490-39e7f618-cb84-11e7-968a-5917bdaf7a80.png)

This is how **Ambiance** currently looks and adds a button surround when hovered.

![notebooks-ambiance](https://user-images.githubusercontent.com/304639/32944649-2cc061d8-cb88-11e7-9dd1-dbf9054f9597.png)

Which is broadly consistent with how notebooks look in GTK+2 using Ambiant-MATE. This is from Geany:

![notebook-gtk2](https://user-images.githubusercontent.com/304639/32944759-840daf54-cb88-11e7-9993-4a9d3ba0b1e1.png)

**Comment by flexiondotorg** [comment]
Closed via https://github.com/ubuntu-mate/ubuntu-mate-artwork/commit/c92b32c0b812cf2d4911614a468fd27fd230e158
