### ISSUE TITLE
Cursor almost invisible while renaming files in Caja with Ambiant-MATE-Dark

### ISSUE THREAD

**Issue by ltcmdata** [ubuntu-mate/ubuntu-mate-artwork#19]
#### Expected behaviour
The cursor should be clearly visible.

#### Actual behaviour
Cursor is almost the same color as the background, so practically invisible.

#### Steps to reproduce the behaviour
Choose Ambiant-Mate-Dark as theme. Rename a file in Caja.

#### MATE general version
1.18.0

#### Linux Distribution
Ubuntu MATE 17.10

**Comment by raveit65** [comment]
Please test https://github.com/ubuntu-mate/ubuntu-mate-artwork/pull/24

**Comment by flexiondotorg** [comment]
Fixed via #24
