### ISSUE TITLE
Clock applet doesn't honor transparent panel background

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-artwork#21]
The Clock applet on a transparent panel is not transparent when using the Ambiant-MATE and Ambiant-MATE Dark, Radiant-MATE does honor the transparent background.

![transparent panel](https://user-images.githubusercontent.com/304639/36899135-a54dab12-1e15-11e8-842c-258576f2a2dd.png)

**Comment by Dolsilwa** [comment]
In mate-applications.css, in "clock-applet" (line 275), changing background-color to transparent or inherit solves this problem. After change it should look like this: 

/* clock-applet */
.mate-panel-menu-bar #PanelApplet #clock-applet-button.flat.toggle,
.mate-panel-menu-bar #PanelApplet #clock-applet-button.flat.toggle:hover {
    background-color: transparent;
    background-image: none;
    border-width: 0;
    color: @dark_fg_color;
    text-shadow: 0 -1px shade (@dark_bg_color, 0.6);
    padding: 3px 5px 3px 5px;
    border: 1px solid transparent;
}

**Comment by flexiondotorg** [comment]
Thank you for the solution @Dolsilwa :smile:

**Comment by raveit65** [comment]
For the record, this issue was introduced by maintainer wish :)
https://github.com/ubuntu-mate/ubuntu-mate-artwork/issues/2
https://github.com/ubuntu-mate/ubuntu-mate-artwork/commit/f283a6db604c9468e06aa44750edcc9cb90ac8d0
