### ISSUE TITLE
Ambiant-MATE and Radiant-MATE CSD 

### ISSUE THREAD

**Issue by brokoli-mate** [ubuntu-mate/ubuntu-mate-artwork#26]
close,minimize,maximize buttons have ellipse, but not circle form.

**Comment by Dolsilwa** [comment]
Hi,
Maybe this not solve this problem and is only a workaround, but i've added those lines to gtk-widgets.css:

.titlebar button.titlebutton {
    margin-left: -2px;
    margin-right: -2px;
    min-width: 15px;
    min-height: 15px;
    max-width: 15px;
    max-height: 15px;
}

And now my titlebuttons in headerbar looks correctly:
![zrzut ekranu z 2018-05-20 17-39-35](https://user-images.githubusercontent.com/36594353/40280537-4815c1ae-5c55-11e8-883b-34c453da1a97.png)
