### ISSUE TITLE
Insensitive menu entries are "blurry" in Radiant-MATE

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-artwork#27]
When using the Radiant-MATE theme, insensitive menu items have a blurred font.

![menu_002](https://user-images.githubusercontent.com/304639/38030009-4f765156-328f-11e8-9ee3-feb42e46d452.png)

You can `apt install geany` and then use `geany` as the test case.

This bug was originally raised in Launchpad:

  * https://bugs.launchpad.net/ubuntu/+source/ubuntu-mate-artwork/+bug/1749750

@raveit65 Please can you take a look.

**Comment by raveit65** [comment]
Why geany? Pluma is the rule :)
This is simply a text-shadow.
It looks a bit weird if grey out with insensitive state.

**Comment by raveit65** [comment]
Please test.

**Comment by flexiondotorg** [comment]
Perfect, thank you!
