### ISSUE TITLE
Checked checkboxes in Radiant-MATE menus are illegible

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-artwork#28]
Using the Radiant-MATE theme, Open Caja and look a the View menu. Any check boxes in the menu are a white icon and difficult to see on the light background.

![menu_001](https://user-images.githubusercontent.com/304639/38030588-e9e4db3a-3290-11e8-9ffd-10d161959be1.png)

This bug was originally raised on Launchpad:

  * https://bugs.launchpad.net/ubuntu/+source/ubuntu-mate-artwork/+bug/1749749

@raveit65 Please can you take a look

**Comment by raveit65** [comment]
Please test
https://github.com/ubuntu-mate/ubuntu-mate-artwork/pull/32

**Comment by flexiondotorg** [comment]
Looks great, thank you!
