### ISSUE TITLE
Ambiant-MATE-Black has unreadible fonts in detect monitor labels

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-artwork#29]
When using Ambiant-MATE-Dark and then opening Monitor Preferences and clicking **Detect monitors** the monitor tags are very hard to read.

![detect_monitor](https://user-images.githubusercontent.com/304639/38031036-32d140da-3292-11e8-90da-35598a763750.png)

This bug was originally posted on Launchpad:

  * https://bugs.launchpad.net/ubuntu/+source/ubuntu-mate-artwork/+bug/1706947

@raveit65 Please can you take a look.

**Comment by raveit65** [comment]
Please review https://github.com/mate-desktop/mate-desktop/pull/309

**Comment by flexiondotorg** [comment]
Thanks @raveit65! mate-desktop/mate-desktop#309 works a treat!
