### ISSUE TITLE
Brisk Menu session buttons are rectangular and not a consistent size

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-artwork#30]
The session action buttons at the buttons of Brisk Menu are rectangular, no the same size as each other and don't match the button styling used elsewhere. This issue affects Ambiant-MATE, Ambiant-MATE-Dark and Radiant-MATE.

![brisk-session-buttons](https://user-images.githubusercontent.com/304639/38031783-faf751b6-3293-11e8-95ef-0ae43c88cee1.png)

Instead of the solid green can the buttons be styled like those in the toolbar of Page 2 of the `gtk3-widget-factory`?

![toolbar-buttons](https://user-images.githubusercontent.com/304639/38032024-8aee1f48-3294-11e8-98c7-6b4d123ba670.png)

@raveit65 Please can you take a look at this?

**Comment by raveit65** [comment]
@ikeydoherty
Can we have a styleclass for this button?
To make it possible to use a independent button styling without matching the buttons in categories/apps-list.

Edit: sadly your application isn't viewable with gtk3-inspector.

**Comment by raveit65** [comment]
@flexiondotorg 
First you need to add this commit to your build
https://github.com/solus-project/brisk-menu/pull/89
Then i can style the session buttons.

**Comment by raveit65** [comment]
https://github.com/ubuntu-mate/ubuntu-mate-artwork/pull/34
Please test.
Maybe you like to use this patch for ubuntu too?
https://www.dropbox.com/s/973d10keqckcge9/brisk-menu_0001-classic-use-standard-log-out-icon.patch?dl=0
This brings back the normal log-out icon.

**Comment by flexiondotorg** [comment]
Much better. Thank you!
