### ISSUE TITLE
migrating Ambiant-MATE-Dark to official themes repo

### ISSUE THREAD

**Issue by jt1796** [ubuntu-mate/ubuntu-mate-artwork#36]
This isn't a real issue, but was wondering if there are any objections to moving the Ambiant-MATE-Dark theme (https://github.com/ubuntu-mate/ubuntu-mate-artwork/tree/master/usr/share/themes/Radiant-MATE) into the official mate themes (https://github.com/mate-desktop/mate-themes/tree/master/desktop-themes). I'll move it if none. 

The reason I ask is because I think this theme is really good, and it would be nice to have it on any system, not just ubuntu mate. I don't think there's any specific ubuntu branding.

**Comment by flexiondotorg** [comment]
These themes are maintained by the Ubuntu MATE team. Upsteam MATE have limited resources and don't have the capacity to maintain additional themes.
