### ISSUE TITLE
Blank Background for LightDM GTK+ Greeter on Bionic

### ISSUE THREAD

**Issue by evancox10** [ubuntu-mate/ubuntu-mate-artwork#37]
I think there's a missing dependency when using the theme for LightDM GTK+ Greeter provided in this package on bionic. The [MATE theme conf file](https://github.com/ubuntu-mate/ubuntu-mate-artwork/blob/master/etc/lightdm/lightdm-gtk-greeter.conf.d/99_ubuntu-mate.conf) for gtk-greeter specifies the wallpaper `/usr/share/backgrounds/ubuntu-mate-artful/Ubuntu-Mate-Northern-Lights.jpg`. However, your dependent package [ubuntu-mate-wallpapers](https://packages.ubuntu.com/bionic/ubuntu-mate-wallpapers) does not include this file in Bionic.

So, the conf file should either be updated to point to one of the wallpapers provided in ubuntu-mate-wallpapers on bionic, or add ubuntu-mate-wallpapers-artful as a dependency.

Thanks!

**Comment by flexiondotorg** [comment]
Since Ubuntu MATE 17.10 we've used slick-greeter. Upgrades from earlier releases should have removed `lightdm-gtk-greeter` but if that package was not automatically removed from your system please do so manually 🙂
