### ISSUE TITLE
eOS window decoration theme: glitches when using Compiz

### ISSUE THREAD

**Issue by mdmayfield** [ubuntu-mate/ubuntu-mate-artwork#38]
I'm afraid I don't know exactly which project owns this; it looks like it could be here, mate-desktop/mate-themes, or somewhere in the Compiz or Elementary projects. If this is not the right place, can anyone please help point me in the right direction?

This is Ubuntu MATE 18.04 LTS, latest package updates as of 2018-07-14.

## Issue
On Marco or no compositor, the eOS window decorations look mostly correct, like this:
![marco - no issue](https://user-images.githubusercontent.com/26154258/42727611-c6b60876-876f-11e8-8c61-c0730674222c.png)

But with Compiz, the decorations are incorrect, like this:
![compiz - issue](https://user-images.githubusercontent.com/26154258/42727614-d4927204-876f-11e8-9d7b-8b00702aa697.png)

## Steps to reproduce
Should be fairly clear from the screenshots:

1. `Appearance Preferences` -> `Customize` -> `Window Border` -> `eOS`
2. `MATE Tweak` -> `Windows` -> `Compiz (Advanced GPU accelerated desktop effects)`

**Comment by flexiondotorg** [comment]
The theme you reference is not part of this project.
