### ISSUE TITLE
Ambiant-Mate Theme GTK.css error Junk

### ISSUE THREAD

**Issue by ghost** [ubuntu-mate/ubuntu-mate-artwork#39]
I use "Ambiant-Mate" Theme and have got errors in Log-File-Manager:

mate-notificati[14624]: Theme parsing error: gtk.css:27:49: Junk at end of value for background-color
mate-notificati[14624]: Theme parsing error: gtk.css:40:55: Junk at end of value for background-color
mate-notificati[14624]: Theme parsing error: gtk.css:48:54: Junk at end of value for background-color
mate-notificati[14624]: Theme parsing error: gtk.css:59:58: Junk at end of value for background-color
mate-notificati[14624]: Theme parsing error: gtk.css:66:28: The :prelight pseudo-class is deprecated. Use :hover instead.
mate-notificati[14624]: Theme parsing error: gtk.css:70:46: Junk at end of value for background-color
mate-notificati[14624]: Theme parsing error: gtk.css:77:35: The :prelight pseudo-class is deprecated. Use :hover instead.
mate-notificati[14624]: Theme parsing error: gtk.css:81:58: Junk at end of value for background-color
mate-notificati[14624]: Theme parsing error: gtk.css:123:31: The :insensitive pseudo-class is deprecated. Use :disabled instead.
mate-notificati[14624]: Theme parsing error: gtk.css:124:24: The :insensitive pseudo-class is deprecated. Use :disabled instead.
mate-notificati[14624]: Theme parsing error: gtk.css:156:27: The :insensitive pseudo-class is deprecated. Use :disabled instead.
mate-notificati[14624]: Theme parsing error: gtk.css:157:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.
mate-notificati[14624]: Theme parsing error: gtk.css:177:34: The :insensitive pseudo-class is deprecated. Use :disabled instead.
mate-notificati[14624]: Theme parsing error: gtk.css:199:34: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

How can I fix that?

**Comment by flexiondotorg** [comment]
What version of Ubuntu MATE are you using?

**Comment by ghost** [comment]
18.04 with 4.15.0-38-generic

installed:
mate-themes - 3.22.16-4ubuntu1
ubuntu-mate-icon-themes - 18.04.11
ubuntu-mate-themes - 18.04.11

**Comment by flexiondotorg** [comment]
Which log file are you seeing these messages in? I can't reproduce the issue.

**Comment by ghost** [comment]
when I type in terminal "caja or opera etc."

terminal shows:
(opera:51773): Gtk-WARNING **: 18:53:28.467: Theme parsing error: gtk.css:27:49: Junk at end of value for background-color

(opera:51773): Gtk-WARNING **: 18:53:28.467: Theme parsing error: gtk.css:40:55: Junk at end of value for background-color

(opera:51773): Gtk-WARNING **: 18:53:28.467: Theme parsing error: gtk.css:48:54: Junk at end of value for background-color

(opera:51773): Gtk-WARNING **: 18:53:28.468: Theme parsing error: gtk.css:59:58: Junk at end of value for background-color

(opera:51773): Gtk-WARNING **: 18:53:28.468: Theme parsing error: gtk.css:66:28: The :prelight pseudo-class is deprecated. Use :hover instead.

(opera:51773): Gtk-WARNING **: 18:53:28.468: Theme parsing error: gtk.css:70:46: Junk at end of value for background-color

(opera:51773): Gtk-WARNING **: 18:53:28.468: Theme parsing error: gtk.css:77:35: The :prelight pseudo-class is deprecated. Use :hover instead.

(opera:51773): Gtk-WARNING **: 18:53:28.468: Theme parsing error: gtk.css:81:58: Junk at end of value for background-color

(opera:51773): Gtk-WARNING **: 18:53:28.468: Theme parsing error: gtk.css:123:31: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(opera:51773): Gtk-WARNING **: 18:53:28.468: Theme parsing error: gtk.css:124:24: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(opera:51773): Gtk-WARNING **: 18:53:28.468: Theme parsing error: gtk.css:156:27: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(opera:51773): Gtk-WARNING **: 18:53:28.468: Theme parsing error: gtk.css:157:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(opera:51773): Gtk-WARNING **: 18:53:28.468: Theme parsing error: gtk.css:177:34: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(opera:51773): Gtk-WARNING **: 18:53:28.468: Theme parsing error: gtk.css:199:34: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.

**Comment by ghost** [comment]
How can I fix the gtk.css errors?

**Comment by flexiondotorg** [comment]
This is a bug in Opera, not the Ubuntu MATE themes.
