### ISSUE TITLE
MonoSpaced text in GtkSourceView context menus

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-artwork#41]
Monospaced text appears in Gedit's (and Pluma < 1.22) content menu. 

![ambiant-gedit-content-menu](https://user-images.githubusercontent.com/304639/57491906-a0dd9000-72b6-11e9-9450-7cbd1a6ede2c.png)

It is caused by theming of GtkSourceView component, see the bug for details:

  * https://gitlab.gnome.org/GNOME/gtksourceview/issues/52

And this commit for more information:

  * https://gitlab.gnome.org/GNOME/gtk/commit/624ec0fb7d5329261dd0c4a991c7889a70c61535

The issue:

  * Exists with the following themes - Ambiant-MATE, Ambiant-MATE-Dark, BlackMATE, GreenLaguna, Radiant-MATE, TraditionalGreen, TraditionalOk;
  * Does not exist with BlueMenta, Blue-Submarine, Green-Submarine, High Contrast, High Contrast Inverse, Menta.

Additional reference:
  * https://ubuntu-mate.community/t/ubuntu-mate-19-04-beta-is-out/19224/11?u=wimpy
  * https://bugs.launchpad.net/ubuntu/+source/ubuntu-mate-artwork/+bug/1823550

tagging @raveit65

**Comment by raveit65** [comment]
Please test https://github.com/ubuntu-mate/ubuntu-mate-artwork/pull/51
