### ISSUE TITLE
Small Folder expansion arrows

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-artwork#42]
The arrows used to expand folders are very small, and not vertically centred, when using the Ambiant-MATE, Ambiant-MATE Dark and Radiant-MATE themes:

**Ambiant-MATE**

![ambiant-folder-arrows](https://user-images.githubusercontent.com/304639/57492257-1302a480-72b8-11e9-8cab-23b8161d34d9.png)

**Blue SubMarine**

![submarine-folder-arrows](https://user-images.githubusercontent.com/304639/57492269-20b82a00-72b8-11e9-92bc-254aef1b2818.png)

tagging @raveit65

**Comment by raveit65** [comment]
Please test and let me know which expander size you prefer.
https://github.com/ubuntu-mate/ubuntu-mate-artwork/pull/50
