### ISSUE TITLE
Headerbar divider is not correctly styled

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-artwork#43]
GNOME Disks and Tilix Preferences use a headerbar divider that is not correctly styled in the Ambiant-MATE and Radiant-MATE themes. The Ambiant-MATE Dark theme looks OK, probably by accident :wink: 

![ambiant-headerbar-divider](https://user-images.githubusercontent.com/304639/57492357-6bd23d00-72b8-11e9-9f1c-ce5e04b1c523.png)

tagging @raveit65

**Comment by raveit65** [comment]
https://github.com/ubuntu-mate/ubuntu-mate-artwork/pull/49
Please test.
