### ISSUE TITLE
Tilix context menu incorrect button styling in popover.

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-artwork#44]
The Tilix terminal split screen button is not correctly styled in the context menu popover when the button is not being hovered over. 

**Not hovering**

![ambiant-tilix-context-nothover](https://user-images.githubusercontent.com/304639/57492501-ec913900-72b8-11e9-9f2a-c5ee93087cc8.png)

**Hovering**

![ambiant-tilix-context-hover](https://user-images.githubusercontent.com/304639/57492508-ef8c2980-72b8-11e9-863a-47a851f4660e.png)

This issue affect Ambiant-MATE and Ambiant-MATE Dark. Radiant MATE is fine.

tagging @raveit65

**Comment by raveit65** [comment]
This is different with 19.04 again. Looks good for me with Ambient-Mate and A-M-D and Radiant-Mate use a non color button.
![Ambiant-mate](https://user-images.githubusercontent.com/961604/57537514-b8fcf000-7346-11e9-81d9-99c248da5a92.png)
![a-m-d](https://user-images.githubusercontent.com/961604/57537525-c023fe00-7346-11e9-938a-e7992e7b2658.png)
![r-m](https://user-images.githubusercontent.com/961604/57537539-c914cf80-7346-11e9-9939-6cff9bb8b544.png)

**Comment by flexiondotorg** [comment]
The issue is only present when *not* hovering over the button.

**Comment by raveit65** [comment]
My guess is that we see the `suggested-action` styling for a button, probably a change in `popover` widget of gtk+ or Tilix.
What do want to see if button is in normal state?
Same like with 19.04?

**Comment by raveit65** [comment]
https://github.com/ubuntu-mate/ubuntu-mate-artwork/pull/48
Please test.
