### ISSUE TITLE
Text selection in dialog windows have low contrast

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-artwork#45]
Launch `mate-terminal`, select *Help*, *About*, select text *A terminal emulator for the MATE desktop*.

Expected results:

* selected text has good contrast

![traditional-dialog-selection](https://user-images.githubusercontent.com/304639/57492840-578f3f80-72ba-11e9-9dd5-b221da7af7a2.png)

Actual results:

* selected text has low contrast

![ambiant-dialog-selection](https://user-images.githubusercontent.com/304639/57492852-5fe77a80-72ba-11e9-9a30-02d5a2203bce.png)

This issue affects Ambiant-MATE, Ambiant-MATE-Dark and Radiant-MATE.

Additional reference:
  * https://ubuntu-mate.community/t/ubuntu-mate-19-04-beta-is-out/19224/11?u=wimpy
  * https://pad.lv/1763942

tagging @raveit65

**Comment by raveit65** [comment]
This should fix the issue. Please test.
Sorry i forgot to open a PR :)
