### ISSUE TITLE
Inconsistent OK button styling

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-artwork#46]
On Ubuntu MATE 19.10 with MATE Desktop 1.22, OK buttons are not styled consistently when using the Ambiant MATE, Ambiant MATE Dark and Radiant MATE themes. See this example where the OK button in *Appearance Preferences* is correctly styled but the OK button in *Startup Applications* has a small `x` instead.

![ambiant-close-buttons](https://user-images.githubusercontent.com/304639/57497202-93340480-72ce-11e9-934e-e4503fb1f52d.png)

Themes from `mate-themes` all work correctly.

tagging @raveit65

**Comment by raveit65** [comment]
Please test https://github.com/ubuntu-mate/ubuntu-mate-artwork/pull/47
