### ISSUE TITLE
Some inactive applications introduce strange rendering

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-artwork#5]
When the following applications do not have focus the fonts are dimmed and some elements are shaded:

  * `mate-control-center`
  * `dconf-editor`

All 3 themes are affected. An example screen shot show the issues is below:

![inactive-apps](https://user-images.githubusercontent.com/304639/29281502-300eba76-8117-11e7-8166-7235d1ee2df9.png)

Tagging @raveit65

**Comment by raveit65** [comment]
Screenshots are made with which WM?
I guess it isn't marco. Sounds like old missing :backdrop style issue with compiz/metacity.

**Comment by flexiondotorg** [comment]
Screen shots made with Compiz.

**Comment by raveit65** [comment]
Please test https://github.com/ubuntu-mate/ubuntu-mate-artwork/commit/67852e8b70fa4b61eb6a7e3fe7b4f6fd8f890c6c

**Comment by flexiondotorg** [comment]
Lovely! The problem application are fixed :-) I close this as testing some application in the past that had this issue are also still working correctly.
