### ISSUE TITLE
feature request: port human-theme to GTK3 and ship it as part of MATE themes

### ISSUE THREAD

**Issue by N0rbert** [ubuntu-mate/ubuntu-mate-artwork#53]
I'm not sure how many people will be happy as the result, but for me it would be really great if MATE will port `human-theme` to GTK3 and include it to theme package.
There is already a good guide for doing so [on AskUbuntu](https://askubuntu.com/a/1115019/66509).

It transforms broken gray theme
 ![](https://i.stack.imgur.com/PJMAT.png)
into nice looking orange  theme
![](https://i.stack.imgur.com/WDj4q.png)

**Comment by flexiondotorg** [comment]
Sorry, the Ubuntu MATE team will not be taking on the responsibility of uplifting old 3rd party GTK2 themes to GTK3, it is simply too much work.

**Comment by N0rbert** [comment]
OK, no problem :) 
May be I'll create a PPA for this pretty nice old theme :)
