### ISSUE TITLE
Gedit popover with Radiant-MATE doesn't  highlight hover over

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-artwork#56]
This issue appears to be related to #44 and only affects the Radiant-MATE theme. When hovering over buttons in popovers, there is no obvious distinction.

## Radiant MATE

There is no obvious change in button presentation as you hover the mouse between the Undo, Print and Fullscreen buttons.

![gedit-radiant-mate-popover](https://user-images.githubusercontent.com/304639/58088396-8494f980-7bba-11e9-9052-357a407419af.png)

## Ambiant-MATE 

Ambiant-MATE (and the dark variant) present an obvious change as buttons in popovers are hovered over.

![gedit-ambiant-mate-popover](https://user-images.githubusercontent.com/304639/58088764-3f24fc00-7bbb-11e9-9ac2-da9d2ae8a7c9.png)

tagging @raveit65

**Comment by raveit65** [comment]
This normal button style for Radiant theme.
Or do you see a normal green button somewhere else when hovering?
For me only the green border when hovering looks wrong.
But if you like to have a green button for popovers i can change that :)

**Comment by flexiondotorg** [comment]
A green border would be fine, but I don't see 🙈 anything obvious right now 🙂

**Comment by raveit65** [comment]
This is with 19.10 here.
![gedit-randiant-mate-19 10](https://user-images.githubusercontent.com/961604/58260128-30cf0f80-7d76-11e9-80f2-c0a39b59bced.jpg)
I will improve it.
Ok, latest Radiant-Mate from master doesn't have this border :)
Edit again:
When gedit is in foreground i see those thin green border lines.
