### ISSUE TITLE
GtkTreeView: sometimes "hover" style overrides "selected" style

### ISSUE THREAD

**Issue by gabrielfin** [ubuntu-mate/ubuntu-mate-artwork#58]
Using Ambiant-MATE (or Ambiant-MATE-Dark), GtkTreeView rows have a light green background when hovered, and a dark green background when selected. A row that is selected *and* hovered should use the dark background. Most of the time that works ok, but sometimes the light background is used.

Here is a video reproducing the issue: 
https://i.imgur.com/rQxtMR8.mp4

**Steps to reproduce:**
1. Enable Ambiant-MATE theme
2. Open mate-system-monitor
3. Select the "Processes" tab
4. Click on any process. It is highlighted with a dark green background.
5. Switch to another tab and then back to "Processes"
6. Hover over the process selected in step 3

**Expected results:**
Hovering should still show the dark green background color

**Actual results:**
Hovering shows the light background color.

I believe this happens with any GtkTreeView, not just mate-system-monitor.

I'm using ubuntu-mate-themes 19.10.2

**Comment by flexiondotorg** [comment]
Sorry, Ambiant-MATE and Radiant-MATE will not be getting any further updates.
