### ISSUE TITLE
Missing icon for secure wired and secure wireless connections

### ISSUE THREAD

**Issue by fedemp** [ubuntu-mate/ubuntu-mate-artwork#59]
When I'm connected to a VPN, even through a wireless or wired connection, the connection in icon the status area does not show a lock. However it does while connecting.

Using out-of-the-box Ubuntu Mate 19.04

Similar issues:
* https://github.com/shimmerproject/elementary-xfce/issues/104
* https://bugs.launchpad.net/ubuntu/+source/xubuntu-artwork/+bug/1796183

**Comment by flexiondotorg** [comment]
Fixed via 8c4389338f5f3bff52c15cdd8770c814a0ca9aa7
