### ISSUE TITLE
metacity-theme-viewer has no header bar at all

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-artwork#6]
After installing `sudo apt install metacity` and running `metacity-theme-viewer` it has no header bar. All 3 Ubuntu MATE themes are affected, as are all the themes from `mate-themes`.

**Comment by raveit65** [comment]
I see the same with all our themes and Ambiance/radiance, but not with Adwaita.
Setting something like this in themes helps a lot.
headerbar.titlebar {
    min-height: 40px;
}

But i never saw this with other CSD windows, so i think its more a code bug.
Well, i can add such a setting to all Mate (including ubuntu-mate) themes, but this does not fix the issue outside MATE world.
@muktupavels
thoughts?

**Comment by muktupavels** [comment]
It seems that GTK+ does not like GtkComboBoxText in header bar... I will probably move combo boxes out of header bar for 3.26.

**Comment by raveit65** [comment]
Please test https://github.com/ubuntu-mate/ubuntu-mate-artwork/commit/aaeffb201020839744d7e7523bd75103d8f62f64

**Comment by flexiondotorg** [comment]
Works great in all 3 themes. Thank you!

**Comment by muktupavels** [comment]
Metacity 3.26 does not use combo box in theme viewer. :)
