### ISSUE TITLE
Firefox wrong window buttons with CSD

### ISSUE THREAD

**Issue by medmedin2014** [ubuntu-mate/ubuntu-mate-artwork#60]
When using Firefox 69.0.2 with CSD and selecting Ambiant or Radiant themes, the window buttons are not displayed correctly, I use Ubuntu Mate 19.10 - 64bits.
![Screenshot at 2019-10-05 00-26-05](https://user-images.githubusercontent.com/7027319/66254552-a5c44400-e76f-11e9-8d68-dbabe1a5c792.png)

![Screenshot at 2019-10-05 10-27-23](https://user-images.githubusercontent.com/7027319/66254554-aceb5200-e76f-11e9-94f1-d5050549d381.png)

**Comment by flexiondotorg** [comment]
Sorry, Ambiant-MATE and Radiant-MATE will not be getting any further updates.
