### ISSUE TITLE
Unfocused text label hard to read on Caja desktop

### ISSUE THREAD

**Issue by lah7** [ubuntu-mate/ubuntu-mate-artwork#62]
[19.10.10] On the Caja desktop, the background and text colour clash when selecting an icon and setting focus on a different window.

![image](https://user-images.githubusercontent.com/13032135/66525336-14492f00-eaed-11e9-8a59-ce66568e5b91.png)

The text/background colour doesn't clash within Caja windows though.

![image](https://user-images.githubusercontent.com/13032135/66525472-7efa6a80-eaed-11e9-8066-2e80960dfe83.png)

**Comment by RudraSwat** [comment]
Yeah, find that strange too... But when using a Zenbook Duo (my main dual-display work laptop), it is the reverse. The text is black and the selection becomes black. This way, you cannot read at all. The text is not visible at all.

![Desktop](https://user-images.githubusercontent.com/26926757/75339734-1999f100-58b7-11ea-8b67-f8fc0bb2fbee.png)

In Caja, it is better like you said.

![Caja](https://user-images.githubusercontent.com/26926757/75339881-61b91380-58b7-11ea-809b-7e960e1b3bef.png)

The Raspberry Pi 3B+ which I'm currently using for testing purposes, though, is like your system completely. Graphics rendering issues, I think.

**Comment by lah7** [comment]
I think I've found some CSS that would "fix" the situation... the trouble is, it doesn't work when put into the theme file! Something else is forcing the white text due to the cascading nature of CSS.

```
.caja-desktop.view :selected:backdrop {
    background-color: @theme_unfocused_bg_color;
    color: @theme_unfocused_fg_color;
}
```

I find it odd since the **Ambiant-MATE-Dark** theme works OK, and they're pretty similar. **Radiant-MATE** suffers from this bug too.
