### ISSUE TITLE
"Create reminder" dropdown in Evolution is not readable

### ISSUE THREAD

**Issue by fedemp** [ubuntu-mate/ubuntu-mate-artwork#63]
![Screenshot at 2019-11-05 16-19-36](https://user-images.githubusercontent.com/735314/68241168-f89e4f00-ffec-11e9-8a6a-ecd3486e318a.png)

To reproduce:
* Open Evolution (no need to create an account).
* Select from the menu: File > New > Appointment
* Select "Reminders" tab
* Click the "+" button.

Aside from the inputs having light grey text on white, should buttons also have a dark background to match the dropdown?

**Comment by flexiondotorg** [comment]
Sorry, Ambiant-MATE and Radiant-MATE will not be getting any further updates.
