### ISSUE TITLE
Package for Flatpak

### ISSUE THREAD

**Issue by stuartlangridge** [ubuntu-mate/ubuntu-mate-artwork#64]
When flatpak packages are installed, they do not honour the system theme on Ubuntu MATE. Flatpak apparently will install a flatpak package of a theme if there is one available so that apps look correct on a given desktop, but the Ubuntu MATE themes are not so packaged and so they're not available. It seems that a theme should be packaged as `org.gtk.Gtk3theme.*`, so `org.gtk.Gtk3theme.Ambiance-MATE` for the Ubuntu MATE Ambiance theme. If this were packaged and released on flatpak then flatpak-installed apps would look correct on an Ubuntu MATE desktop.

**Comment by nothingneko** [comment]
I can take this over if you'd like, I'll cut the wallpapers and unnecessary bits.

**Comment by flexiondotorg** [comment]
Fixed via:

  * https://github.com/flathub/org.gtk.Gtk3theme.Yaru-MATE-dark
  * https://github.com/flathub/org.gtk.Gtk3theme.Yaru-MATE

**Comment by gnat** [comment]
Thank you @flexiondotorg !!

Suggestion: Since flatpak is default in MATE 22.04, would be really cool if `org.gtk.Gtk3theme.Yaru-MATE-dark` got installed alongside Yaru-MATE-dark theme so people don't need to google this ticket.

**Comment by nothingneko** [comment]
> Thank you @flexiondotorg !!
> 
> 
> 
> Suggestion: Since flatpak is default in MATE 22.04, would be really cool if `org.gtk.Gtk3theme.Yaru-MATE-dark` got installed alongside Yaru-MATE-dark theme so people don't need to google this ticket.

As far as I know Flatpak with automatically install the theme as needed
