### ISSUE TITLE
Indicator Applet wifi vpn icon

### ISSUE THREAD

**Issue by ghost** [ubuntu-mate/ubuntu-mate-artwork#65]
![Screenshot at 2020-04-10 17-49-27](https://user-images.githubusercontent.com/60102375/79495283-a8f49280-8024-11ea-8c02-c60913cd2556.png)

After connected to vpn wifi icon disappears in network-manager indicator

**Comment by lah7** [comment]
Attempted to add [some missing icons](https://github.com/ubuntu-mate/ubuntu-mate-artwork/commit/9dc132a35744ceb593963c1bff6a264b79e57511) from `ubuntu-mono-dark` and `ubuntu-mono-light`, but still not showing in 20.04. 19.10 is fine. Needs further investigation.

**Comment by ghost** [comment]
When changed to new colors theme like  Ambiant Orange or Purple icon shows right. Screenshot with new theme.
![Screenshot at 2020-04-17 06-51-11](https://user-images.githubusercontent.com/60102375/79533458-36150700-8078-11ea-83ba-8c7d7eb64b2c.png)
 right

**Comment by lah7** [comment]
Hmm, that's even more confusing - the [`ubuntu-mate-colours`](https://github.com/lah7/ubuntu-mate-colours) project is pretty much an overlay that inherits Ambiant-MATE. :confused:

**Comment by flexiondotorg** [comment]
What version of Ubuntu MATE are you using?

**Comment by ghost** [comment]
20.04

**Comment by pohmelie** [comment]
I approve, that #66 fixes the issue for me. Not sure why it is not merged yet.
