### ISSUE TITLE
Some icons dont fit on the panel properly or they get blurry

### ISSUE THREAD

**Issue by Neverest** [ubuntu-mate/ubuntu-mate-artwork#67]
Been trying out Ubuntu Mate 20.04 and noticed that some icons don't fit the panel properly on certain sizes. From getting cut off to going blurry.

![icons](https://user-images.githubusercontent.com/13340767/81756766-a9007a80-948a-11ea-85b7-6f62bb25b713.gif)
 
Above programs are obs, qbittorrent and keepassxc. Starts on the panels default size which is 28 pixels.

**Comment by flexiondotorg** [comment]
This is not an issue with the Ubuntu MATE artwork package, please raise this bug in https://github.com/mate-desktop/mate-indicator-applet :+1:
