### ISSUE TITLE
missing font colors in Ambiant Mate Dark

### ISSUE THREAD

**Issue by JuliaLawall** [ubuntu-mate/ubuntu-mate-artwork#68]
The xml file with the font colors for Ambiant Mate Dark is missing a lot of information.  Applications then seem to use the system defaults, which results in text, particularly in red and blue, that is unreadable in a dark theme.  Some undefined tags are:

```
def:base-n-integer
def:boolean
def:decimal
def:floating-point
def:shebang
def:type
```
The software that uses the above tags is rather specialized, but I see the same problem with emacs - the messages generated in the line at the bottom of the screen are in dark blue on black and are thus unreadable.

**Comment by flexiondotorg** [comment]
Sorry, Ambiant-MATE and Radiant-MATE will not be getting any further updates.
