### ISSUE TITLE
Ambiant-MATE-Dark - transmission-gtk - TreeView hover text colour too light

### ISSUE THREAD

**Issue by lah7** [ubuntu-mate/ubuntu-mate-artwork#69]
In an application like Transmission, the text colour when **hovering** over the TreeView item is too light.

![Screenshot_20200810_141122](https://user-images.githubusercontent.com/13032135/89786188-73177480-db13-11ea-87c5-e3bfcbb48bca.png)

The **selected** text colour is OK:
![Screenshot_20200810_141352](https://user-images.githubusercontent.com/13032135/89786378-ba056a00-db13-11ea-8101-ad4c425702af.png)

Also affects: https://github.com/lah7/ubuntu-mate-colours/issues/22

**Comment by flexiondotorg** [comment]
Sorry, Ambiant-MATE and Radiant-MATE will not be getting any further updates.
