### ISSUE TITLE
Scrollbar has a dark left edge on Ambiant-MATE

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-artwork#7]
Scrollbars on the Ambiant-MATE theme have a dark, or black, left edge. It should be a lighter colour to better blend in. This issue only affects Ambiant-MATE. I've included screenshots of Ambiant-MATE and Radiant-MATE for comparison

## Ambiant-MATE (wrong)

![pluma-ambiant-mate](https://user-images.githubusercontent.com/304639/29282098-6ab0a5e8-8119-11e7-81d0-465e03eb3369.png)

## Radiant-MATE 

![pluma-radiant-mate](https://user-images.githubusercontent.com/304639/29282108-6e409f74-8119-11e7-8073-6a391b627f7c.png)

Tagging @raveit65

**Comment by raveit65** [comment]
This is really new, i never saw that with 17.04.
Looks like the border color from metacity theme.  -_-

**Comment by raveit65** [comment]
This is caused by https://github.com/ubuntu-mate/ubuntu-mate-artwork/commit/b890d0ed377f677eb4f82e528af5d860b4e04fe0#diff-fa63e3e8515f204d63f72e3b2f376f06R24
Why using such a dark border color?
```
@define-color borders shade(@bg_color, 0.3);
```

**Comment by flexiondotorg** [comment]
@raveit65 I actually can't remember what I was fixing with that. I remember doing it, but recall what I was fixing. Please replace it with something sane.

**Comment by raveit65** [comment]
Please test https://github.com/ubuntu-mate/ubuntu-mate-artwork/commit/6775bf64b2d0faac8b2d6212cf13c253ea6f7e87

> I actually can't remember what I was fixing with that. 

If we need a black border somewhere than we need to create a new single color definition for this,
**borders** is a very general definition and is used in a lot of places.
You can ping me for doing that.

**Comment by flexiondotorg** [comment]
Tested, looks correct again. Thank you! :-)
