### ISSUE TITLE
[>=20.04] Inconsistent tab styles in Synaptic

### ISSUE THREAD

**Issue by lah7** [ubuntu-mate/ubuntu-mate-artwork#71]
Ambiant-MATE and Radiant-MATE have inconsistent tab styles that is not seen with other MATE themes. Ambiant-MATE-Dark is affected too, but is not as bad.

To replicate, install Synaptic and enable "Show package properties in main window" in Preferences.

The tabs on the main window are inconsistent with tabs in the dialog box:

:x: **Affects 20.04/21.04:**

The first set of tabs behind the window has broken styling:

![Screenshot_20210115_104835](https://user-images.githubusercontent.com/13032135/104716281-a643dc80-571f-11eb-9fcf-92ce36b1cf39.png)
![Screenshot_20210115_104812](https://user-images.githubusercontent.com/13032135/104716279-a5ab4600-571f-11eb-9fd4-14f039ffc146.png)

✅  Compared to **18.04**:

![Screenshot_20210115_105418](https://user-images.githubusercontent.com/13032135/104716570-063a8300-5720-11eb-9f9f-34376317e666.png)

Example of 21.04 MATE theme "TraditionalOk":

![Screenshot_20210115_105540](https://user-images.githubusercontent.com/13032135/104716731-371ab800-5720-11eb-9111-9c06ee7921e4.png)

_Although even the padding between the two in this theme isn't perfect, it is more readable then Ambiant/Radiant MATE_

**Comment by lah7** [comment]
Another example is the **GTK+ Demo** (from `gtk-3-examples`)

Here, the "Info" tab is selected.

![Screenshot_20210303_113746](https://user-images.githubusercontent.com/13032135/109800297-e221fb00-7c14-11eb-98ef-8a3ee076de39.png)

**Comment by flexiondotorg** [comment]
Sorry, Ambiant-MATE and Radiant-MATE will not be getting any further updates.
