### ISSUE TITLE
Will Ambiant MATE get updated for GTK 4.0?

### ISSUE THREAD

**Issue by ro1y** [ubuntu-mate/ubuntu-mate-artwork#72]
I prefer Ambiant over Yaru, and I really hope you keep it available for the future.

**Comment by mz1193** [comment]
Even though I like the new Yaru theme myself, I'm seconding this. I know maintaining themes is hard work, but in my opinion the Ambiance theme family is one of the best ever designed and it would be sad to see it fall by the wayside.

**Comment by flexiondotorg** [comment]
Sadly not. Ambiant-MATE and Radiant-MATE will not be getting any future updates.
