### ISSUE TITLE
[Feature request] Add green window buttons to compliment the green theme

### ISSUE THREAD

**Issue by ouryperd** [ubuntu-mate/ubuntu-mate-artwork#73]
Up to 16.04 I used the RaveFinity Ambiance/Radiance themes to get green buttons.

https://www.ravefinity.com/p/download-ambiance-radiance-colors.html

**Comment by flexiondotorg** [comment]
Sorry, Ambiant-MATE and Radiant-MATE will not be getting any further updates. But the new Yaru-MATE themes do use green accents for the window decoration.
