### ISSUE TITLE
[21.04] Yaru-MATE-dark: Incorrect background colour for Caja location text box

### ISSUE THREAD

**Issue by lah7** [ubuntu-mate/ubuntu-mate-artwork#74]
In Caja, press CTRL+L to toggle the location bar. On Yaru-MATE-dark, the text box should be a dark background, but it currently is white and clashes with the text colour.

![Screenshot_20210401_183654](https://user-images.githubusercontent.com/13032135/113332780-88971400-9319-11eb-901d-22401bfbf34b.png)
![Screenshot_20210401_183453](https://user-images.githubusercontent.com/13032135/113332783-89c84100-9319-11eb-84d7-1c898d05c544.png)

Tested with: 21.04.6

**Comment by saivinob** [comment]
I have seen the opposite too. Yaru MATE Light having dark location bar bg. It is happening when we are changing from light to dark or dark to light (but not consistently enough). If we logout and re-login, it gets corrected (for both scenarios). 21.04.6 as well.

![Screenshot at 2021-04-02 19-15-30](https://user-images.githubusercontent.com/54169365/113421768-46d59e80-93e9-11eb-947d-1c01214d3487.png)

![Screenshot at 2021-04-02 19-17-26](https://user-images.githubusercontent.com/54169365/113421818-548b2400-93e9-11eb-9b0b-35fc598e6b13.png)

![Screenshot at 2021-04-02 19-17-13](https://user-images.githubusercontent.com/54169365/113421835-5c4ac880-93e9-11eb-9c5e-79ec520053d7.png)

**Comment by juhler64** [comment]
Went from Yaru Dark to light and can see the issue as well.

![image](https://user-images.githubusercontent.com/70597395/113441886-06f8c200-93bd-11eb-89b5-2f8a9c472925.png)

**Comment by franksmcb** [comment]
Opened issue report with ubuntu/yaru https://github.com/ubuntu/yaru/issues/2772

**Comment by navycatt** [comment]
Ubuntu Mate 22.04 affected too.

**Comment by flexiondotorg** [comment]
This is a bug in Caja, not Yaru. For reasons yet to be established this one element doesn't update on a theme change.

Killing Caja and starting it will refresh the text-based location as will restarting the desktop session or rebooting.
