### ISSUE TITLE
Yaru-Theme does not define colors/icons/gradients which are used by applications

### ISSUE THREAD

**Issue by N0rbert** [ubuntu-mate/ubuntu-mate-artwork#76]
Steps to reproduce:
1. Install Ubuntu MATE 21.10
2. Install gElemental from repository
3. Login to MATE session
4. Launch gelemental

Expected results:
* gelemental is usable, chemical elements has different colors

Actual results:
* gelemental is not usable, chemical elements has single same color

     ![gelemnental_Yaru-light](https://user-images.githubusercontent.com/309456/138597950-07636187-2579-42dc-a891-2d6818606f18.png)

ProblemType: Bug
DistroRelease: Ubuntu 21.10
Package: yaru-theme-gtk 21.10.1
ProcVersionSignature: Ubuntu 5.13.0-14.14-generic 5.13.1
Uname: Linux 5.13.0-14-generic x86_64
ApportVersion: 2.20.11-0ubuntu68
Architecture: amd64
CasperMD5CheckResult: unknown
CurrentDesktop: MATE
Date: Sun Sep 12 19:28:37 2021
PackageArchitecture: all
ProcEnviron:
 TERM=xterm-256color
 PATH=(custom, no user)
 XDG_RUNTIME_DIR=<set>
 LANG=en_US.UTF-8
 SHELL=/bin/bash
SourcePackage: yaru-theme
UpgradeStatus: Upgraded to impish on 2021-09-10 (2 days ago)

Downstream bug-report - https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1943371 .

**Comment by clobrano** [comment]
Hi @N0rbert, thank you for taking time to report this issue.
I noticed - in the launchpad bug - that a fix should be available in the application itself (see [here](https://github.com/ginggs/gelemental/commit/17c3a7fffe19890fc312a33ec2590ce1ac61f2e6))
I think that, if the definitions are used by 1 application only, it is up to the application to the application to provides it.
