### ISSUE TITLE
Snap Apps don't use Yaru MATE Themes

### ISSUE THREAD

**Issue by N0rbert** [ubuntu-mate/ubuntu-mate-artwork#77]
Snap applications including the recently snap'd Firefox do not follow the Yaru MATE theme nor any of its color variations. By default these apps seem to default to Adwaita. It may be worth noting that Firefox uses the current Adwaita theme while Chromium seems to use an old version of the theme. The Ambience MATE themes do work in snap apps with zero extra configuration.

---
ProblemType: Bug
ApportVersion: 2.20.11-0ubuntu69
Architecture: amd64
CasperMD5CheckResult: pass
CurrentDesktop: MATE
DistroRelease: Ubuntu 21.10
InstallationDate: Installed on 2021-09-27 (8 days ago)
InstallationMedia: Ubuntu-MATE 21.10 "Impish Indri" - Beta amd64 (20210923)
Package: ubuntu-mate-meta
ProcVersionSignature: Ubuntu 5.13.0-16.16-generic 5.13.13
Snap: snapd 2.51.7 (latest/stable)
Tags: impish
Uname: Linux 5.13.0-16-generic x86_64
UpgradeStatus: No upgrade log present (probably fresh install)
UserGroups: adm cdrom dip lpadmin lxd plugdev sambashare sudo
_MarkForUpload: True

Downstream bug report - https://bugs.launchpad.net/ubuntu-mate/+bug/1945666 .

**Comment by lah7** [comment]
I'm not sure, but do snap apps require snapped themes to work? The [README](https://github.com/ubuntu-mate/gtk-theme-yaru-mate-snap#readme) for Ubuntu MATE's GTK snap mentions some commands to "connect" them. I found [a blog post on OMGUbuntu! in 2020](https://www.omgubuntu.co.uk/2020/06/change-snap-app-theme) covering the situation too. I could not find any later news if the "automatic" integration was implemented.

A snap for the colourized themes will be created soon, see https://github.com/lah7/ubuntu-mate-colours/issues/27.

**Comment by flexiondotorg** [comment]
The required snaps have been created and published.

  * https://github.com/ubuntu-mate/gtk-theme-yaru-mate-snap
  * https://github.com/ubuntu-mate/icon-theme-yaru-mate-snap

`snapd` still does not feature auto-connection of snapped themes. Closing this issue, as there is nothing for us to fix.
