### ISSUE TITLE
Unwanted infobar border in GNOME Software [Ambiant/Radiant-MATE]

### ISSUE THREAD

**Issue by lah7** [ubuntu-mate/ubuntu-mate-artwork#78]
Originally reported at lah7/Ambiant-MATE#2

The `infobar` in GNOME Software appears to show an unwanted border with colours  `#eaea77` and `#e3e368`. In other themes, the colour is generally the accent colour. Noting as a potential thing for the community to fix.

![Screenshot_20211025_193202](https://user-images.githubusercontent.com/13032135/138750545-b1fa0981-e2b1-48ee-b21b-cf076e45fb40.png)
![Screenshot_20211025_193327](https://user-images.githubusercontent.com/13032135/138750728-c096f49a-5612-4dbe-b327-cd0977ae5c7d.png)
![Screenshot_20211025_193403](https://user-images.githubusercontent.com/13032135/138750799-b053e629-d470-449e-96b2-0063fe791311.png)

**Comment by flexiondotorg** [comment]
Sorry, Ambiant-MATE and Radiant-MATE will not be getting any further updates.
