### ISSUE TITLE
Restyle linked buttons to look more traditional

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-artwork#8]
Please restyle the linked buttons in a `dialog-action-area` and `button.linked.dialog-action-area` so that they have a more traditional appearance. In particular the logout and shutdown dialogue windows are where this is most evident. This issue affects all 3 themes.

The image below is for reference. The logout and shutdown dialogues should be styled to more closer reflect the style GTK2 present, on the right:

![logout](https://user-images.githubusercontent.com/304639/29290018-89efc390-8136-11e7-9eb7-252f3e6fd6d4.png)

Tagging @raveit65

**Comment by flexiondotorg** [comment]
@raveit65 `mate-session-manager` in the 17.10 archive now carries the [the logout-dialog style class patch](https://github.com/mate-desktop/mate-session-manager/commit/1ea1e9cadd8c886c1f3d74275164adf59370f859).

**Comment by raveit65** [comment]
https://github.com/ubuntu-mate/ubuntu-mate-artwork/pull/13

**Comment by flexiondotorg** [comment]
Perfect! Please add to the other themes :-D

**Comment by flexiondotorg** [comment]
I've tested all 3 themes now. Ambiant-MATE and Radiant-MATE look great. However, the button styling in Ambiant-MATE-Dark looks strange, the highlighted button borders are *"too much"*.

![ambiant-mate-dark-logout-buttons](https://user-images.githubusercontent.com/304639/29458281-310c1ca0-8416-11e7-9652-186c50fd396b.png)

Can the buttons be styled to match how they are presented in the `mate-about` dialog?

![ambiant-mate-dark-about](https://user-images.githubusercontent.com/304639/29458277-2d7662c6-8416-11e7-8d77-5fc41e22e728.png)

**Comment by raveit65** [comment]
Branch is rebased with fixed button styling for AD.
Please test again.

**Comment by flexiondotorg** [comment]
Perfect! Thank you :-)

**Comment by ghost** [comment]
Is placing the text inside the progress bar impossible in GTK+ 3?

**Comment by raveit65** [comment]
Was this ever possible with gtk+-2 ?

**Comment by ghost** [comment]
@raveit65 The right-side example :p

**Comment by raveit65** [comment]
I don't think it's possible, btw. there is no otion to display it inside the progressbar here.
https://developer.gnome.org/gtk3/unstable/GtkProgressBar.html
It's only possible to set another text than % value or disable the text.
gtk_progress_bar_set_show_text ()
gtk_progress_bar_set_text ()

**Comment by ghost** [comment]
That's a bummer. The progress bar with text above looks very clunky in gtk+ 3, ever thought of removing it, like it was in GNOME 2?

![lx4rp](https://user-images.githubusercontent.com/13562431/34447111-148f35a6-ecc8-11e7-8fad-ef0baa8abb50.png)

**Comment by raveit65** [comment]
Guys, why not doing this for yourself?
[rave@mother ~]$ gsettings get org.mate.session logout-timeout
0
😃

**Comment by raveit65** [comment]
Or ask your Chief to add this key to mate-tweak.

**Comment by ghost** [comment]
@raveit65 What i am proposing is removing the progress bar, not the logout timeout... Sorry if i'm being inconvenient.

**Comment by raveit65** [comment]
@mrnhmath 
Did you really test this key?
Setting logout-time to zero hides the progressbar.
I am really in doubt that most MATE users wants the progressbar removed in general, only because of a personal style taste.

**Comment by ghost** [comment]
Yes i did! It also removes the "You are currently logged in..." text.

**Comment by lah7** [comment]
I give a +1 to @mrnhmath's suggestion. Instead of a progress bar counting down, it would aesthetically look more like the original experience if the text changed while counting down.

I secretly wish the GTK3 dialogues would look like its GTK2 (GNOME 2) counterparts :blush: (including that icon and left aligned text)

**Comment by ghost** [comment]
I should make a separate issue regarding progress bar removal and the missing icon. 

I don't know why the gtk+ guys thought center aligned text in message dialogs was a good idea 🤷‍♂️  Even elementary had to fork it (Granite.MessageDialog) to maintain a saner experience.
