### ISSUE TITLE
End of scroll shadow looks weird with Ambiant-MATE and Radiant-MATE themes

### ISSUE THREAD

**Issue by N0rbert** [ubuntu-mate/ubuntu-mate-artwork#80]
Steps to reproduce:
1. Have Ubuntu MATE 22.04 LTS daily installed
2. With some application with vertical scroll - for example `mate-keyboard-properties` → Layouts → Options or `mate-appearance-properties`
3. Rotate mouse wheel to the bottom

Expected results:
* resulting scroll shadow is beautiful

Actual results:
* resulting scroll shadow is weird (see screenshots).

![jammy-scroll-Radiant-MATE](https://user-images.githubusercontent.com/309456/147495054-15167209-936c-442f-b403-a05d25216d95.png)
![Ambiant-MATE](https://user-images.githubusercontent.com/309456/147495053-1783eaa6-e03e-4294-85af-893338f7391d.png)

Downstream bug report - https://bugs.launchpad.net/ubuntu/+source/ubuntu-mate-artwork/+bug/1955839 .
Hardware in use - old Lenovo SL500 with 

```
$ lspci -k | grep VGA -A3
00:02.0 VGA compatible controller: Intel Corporation Mobile 4 Series Chipset Integrated Graphics Controller (rev 07)
	Subsystem: Lenovo Mobile 4 Series Chipset Integrated Graphics Controller
	Kernel driver in use: i915
	Kernel modules: i915
```

.

ProblemType: Bug
DistroRelease: Ubuntu 22.04
Package: ubuntu-mate-themes 22.04.0
ProcVersionSignature: Ubuntu 5.13.0-19.19-generic 5.13.14
Uname: Linux 5.13.0-19-generic x86_64
ApportVersion: 2.20.11-0ubuntu74
Architecture: amd64
CasperMD5CheckResult: pass
CurrentDesktop: MATE
Date: Mon Dec 27 19:53:58 2021
InstallationDate: Installed on 2021-12-27 (0 days ago)
InstallationMedia: Ubuntu-MATE 22.04 LTS "Jammy Jellyfish" - Alpha amd64 (20211227)
PackageArchitecture: all
SourcePackage: ubuntu-mate-artwork
UpgradeStatus: No upgrade log present (probably fresh install)

**Comment by flexiondotorg** [comment]
Sorry, Ambiant-MATE and Radiant-MATE will not be getting any further updates.
