### ISSUE TITLE
Some CSD issues with Ambiant Mate theme

### ISSUE THREAD

**Issue by user1-github** [ubuntu-mate/ubuntu-mate-artwork#81]
It seems like some CSD apps don't look properly with Ambiant Mate theme as can be seen in the screenshot (the app is Gnome Disks). There are no rounded corners at the top and the exit, maximize, minimize buttons look ugly. In the screenshots of issue #78 it looks properly (it has rounded corners and the buttons look good). I'm currently on Ubuntu Mate 21.10.

P.S. I really hope that the development of Ambiant Mate theme is not abandoned because while the Yaru theme is also nice, many of us who use an old school desktop like Mate, also want to use it with an old school theme, especially with one of the best like Ambiant. After all, the motto of Ubuntu Mate is "For a retrospective future" ;) 
So it would be highly appreciated if these open issues will be solved and GTK 4 support added as well.
![CSD](https://user-images.githubusercontent.com/56021366/152997344-6f0b1406-4fb6-4e9d-98f1-e256b273c714.png)

**Comment by flexiondotorg** [comment]
Sorry, Ambiant-MATE and Radiant-MATE will not be getting any further updates.
