### ISSUE TITLE
Text caret navigation not visible when renaming a file/folder using Caja Icon View and Yaru-MATE -dark theme

### ISSUE THREAD

**Issue by navycatt** [ubuntu-mate/ubuntu-mate-artwork#83]
Issue https://github.com/ubuntu-mate/ubuntu-mate-artwork/issues/82 not fixed.
I tested ubuntu mate 22.04 with package version ubuntu-mate-artwork 22.04.1. The problem is not solved.
yaru-mate-light with text cursor
![Снимок экрана в 2022-02-27 06-22-59](https://user-images.githubusercontent.com/92228311/156089085-735f0d5a-26d1-4c7a-a73c-d44c70055802.png)
yaru-mate-dark without text cursor
![Снимок экрана в 2022-02-27 06-20-33](https://user-images.githubusercontent.com/92228311/156089128-afbf5d71-7476-48b7-8476-d0fedd9a7585.png)

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/ubuntu/yaru/pull/3431
