### ISSUE TITLE
Text caret navigation not visible when renaming a file/folder on desktop and Yaru-MATE-dark theme

### ISSUE THREAD

**Issue by navycatt** [ubuntu-mate/ubuntu-mate-artwork#84]
22.04, 21.10 Ubuntu Mate, Yaru Mate Dark theme, text caret navigation is not visible while renaming a file on the desktop. Yaru Mate light is ok. 
yaru-mate-light with text caret navigation
![yaru-mate-light](https://user-images.githubusercontent.com/92228311/158736369-33774756-d4af-4df0-9192-191fabb3d72b.png)

yaru-mate-dark without text caret navigation
![yaru-mate-dark](https://user-images.githubusercontent.com/92228311/158736402-1b71f0e9-b604-42da-84a2-59cfe818417b.png)

Previously problem was solved for Caja in issues:
https://github.com/ubuntu-mate/ubuntu-mate-artwork/issues/83
https://github.com/ubuntu-mate/ubuntu-mate-artwork/issues/82.

Now the same problem exists for desktop. It seems that this problem should be solved globally.

Bug: https://bugs.launchpad.net/ubuntu/+source/ubuntu-mate-artwork/+bug/1926094.

**Comment by flexiondotorg** [comment]
This is fixed in 22.04 via https://github.com/ubuntu-mate/ubuntu-mate-artwork/releases/tag/22.04.2

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/ubuntu/yaru/pull/3544
