### ISSUE TITLE
Menus and Caja List View and Caja Side Bar spacing is too cramped

### ISSUE THREAD

**Issue by flexiondotorg** [ubuntu-mate/ubuntu-mate-artwork#9]
Spacing between the following items is slightly too cramped in all 3 Ubuntu MATE themes. 

  * Menus and Context Menus
  * Files and folders displayed in Caja List View
  * The Caja sidebar

Can they each be padded out a little more. The padding used in the Ambiance theme (`sudo apt install light-themes`) is suitable for each case.

Tagging @raveit65

**Comment by raveit65** [comment]
Should be possible to increase the height for menus and treeviews.
Is this a caja only issue or should i adjust this in general?

**Comment by flexiondotorg** [comment]
Well Menus and Context menu changes should be a general change. 

I don't know what else the Caja changes might impact, but I don't see why those changes should not be general for the sake of consistency.

**Comment by flexiondotorg** [comment]
Closed via 39070d1454acff5fe752ce693636b865cec77335
